=== thabz/Kalliope/data/kalliopework.dtd
<!ENTITY AElig "&#198;">
<!ENTITY Auml "&#196;">
<!ENTITY Epsilon "&#917;">
<!ENTITY Gamma "&#915;">
<!ENTITY Iota "&#921;">
<!ENTITY Kappa "&#922;">
<!ENTITY Lambda "&#923;">
<!ENTITY OElig "&#338;">
<!ENTITY Omega "&#937;">
<!ENTITY Omicron "&#927;">
<!ENTITY Pi "&#928;">
<!ENTITY Rho "&#929;">
<!ENTITY Sigma "&#931;">
<!ENTITY Upsilon "&#933;">
<!ENTITY Uuml "&#220;">
<!ENTITY acirc "&#226;">
<!ENTITY aelig "&#230;">
<!ENTITY agrave "&#224;">
<!ENTITY bdquo "&#8222;">
<!ENTITY dagger "&#8224;">
<!ENTITY deg "&#176;">
<!ENTITY eacute "&#233;">
<!ENTITY ecirc "&#234;">
<!ENTITY egrave "&#232;">
<!ENTITY infin "&#8734;">
<!ENTITY iuml "&#239;">
<!ENTITY ldquo "&#8220;">
<!ENTITY mdash "&#8212;">
<!ENTITY nbsp "&#160;">
<!ENTITY ocirc "&#244;">
<!ENTITY oelig "&#339;">
<!ENTITY ouml "&#246;">
<!ENTITY szlig "&#223;">
<!ENTITY thorn "&#254;">

<!ELEMENT kalliopework (workhead, workbody?)>
<!ATTLIST kalliopework
  id CDATA #REQUIRED
  author CDATA #REQUIRED
  status CDATA #IMPLIED
  type CDATA #IMPLIED
  parent CDATA #IMPLIED>

<!ELEMENT workhead ANY>
<!ELEMENT workbody ANY>
<!ELEMENT text ANY>
<!ATTLIST text
  id CDATA #IMPLIED
  variant CDATA #IMPLIED
  aliases CDATA #IMPLIED
  skip-index CDATA #IMPLIED
  lang CDATA #IMPLIED
  ignore-tests CDATA #IMPLIED>
<!ELEMENT poem ANY>
<!ATTLIST poem id CDATA #IMPLIED>
<!ELEMENT prose ANY>
<!ATTLIST prose font-size CDATA #IMPLIED>
<!ELEMENT prosa ANY>
<!ELEMENT section ANY>
<!ATTLIST section
  id CDATA #IMPLIED
  level CDATA #IMPLIED
  variant CDATA #IMPLIED
  aliases CDATA #IMPLIED>
<!ELEMENT subwork ANY>
<!ATTLIST subwork ref CDATA #REQUIRED>
<!ELEMENT content ANY>

<!ELEMENT head ANY>
<!ELEMENT body ANY>
<!ATTLIST body xml:space (default|preserve) "preserve">
<!ELEMENT title ANY>
<!ATTLIST title force-index CDATA #IMPLIED>
<!ELEMENT year ANY>
<!ELEMENT subtitle ANY>
<!ELEMENT suptitle ANY>
<!ELEMENT firstline ANY>
<!ATTLIST firstline force-index CDATA #IMPLIED>
<!ELEMENT indextitle ANY>
<!ELEMENT toctitle ANY>
<!ELEMENT linktitle ANY>
<!ELEMENT breadcrumbtitle ANY>
<!ELEMENT nofirstline ANY>
<!ELEMENT keywords ANY>
<!ELEMENT source ANY>
<!ATTLIST source
  id CDATA #IMPLIED
  in CDATA #IMPLIED
  pages CDATA #IMPLIED
  facsimile CDATA #IMPLIED
  facsimile-pages CDATA #IMPLIED
  facsimile-pages-num CDATA #IMPLIED
  facsimile-pages-offset CDATA #IMPLIED>
<!ELEMENT dates ANY>
<!ELEMENT published ANY>
<!ELEMENT written ANY>
<!ELEMENT performed ANY>
<!ELEMENT event ANY>
<!ELEMENT begivenhed ANY>

<!ELEMENT notes ANY>
<!ELEMENT note ANY>
<!ATTLIST note
  xml:space (default|preserve) "preserve"
  type CDATA #IMPLIED
  lang CDATA #IMPLIED
  unknown-original-by CDATA #IMPLIED>
<!ELEMENT quality ANY>
<!ELEMENT pictures ANY>
<!ELEMENT picture ANY>
<!ATTLIST picture
  src CDATA #IMPLIED
  type CDATA #IMPLIED
  year CDATA #IMPLIED
  artwork CDATA #IMPLIED
  museum CDATA #IMPLIED
  invnr CDATA #IMPLIED
  objid CDATA #IMPLIED
  wikidata CDATA #IMPLIED>

<!ELEMENT poetry ANY>
<!ATTLIST poetry font-size CDATA #IMPLIED>
<!ELEMENT quote ANY>
<!ATTLIST quote
  font-size CDATA #IMPLIED
  margin-left CDATA #IMPLIED>
<!ELEMENT a ANY>
<!ATTLIST a
  href CDATA #IMPLIED
  poet CDATA #IMPLIED
  poem CDATA #IMPLIED
  work CDATA #IMPLIED
  keyword CDATA #IMPLIED
  person CDATA #IMPLIED
  bible CDATA #IMPLIED
  type CDATA #IMPLIED>
<!ELEMENT xref ANY>
<!ATTLIST xref
  poem CDATA #IMPLIED
  bibel CDATA #IMPLIED
  type CDATA #IMPLIED>
<!ELEMENT b ANY>
<!ELEMENT i ANY>
<!ELEMENT sc ANY>
<!ELEMENT small ANY>
<!ELEMENT sup ANY>
<!ELEMENT s ANY>
<!ELEMENT u ANY>
<!ELEMENT num ANY>
<!ELEMENT nonum ANY>
<!ELEMENT resetnum ANY>
<!ELEMENT center ANY>
<!ELEMENT right ANY>
<!ELEMENT margin ANY>
<!ELEMENT metrik ANY>
<!ELEMENT wrap ANY>
<!ELEMENT line ANY>
<!ELEMENT br ANY>
<!ELEMENT hr ANY>
<!ATTLIST hr width CDATA #IMPLIED>
<!ELEMENT pb ANY>
<!ATTLIST pb n CDATA #IMPLIED>
<!ELEMENT img ANY>
<!ATTLIST img
  src CDATA #IMPLIED
  alt CDATA #IMPLIED
  width CDATA #IMPLIED>
<!ELEMENT colored ANY>
<!ATTLIST colored color CDATA #IMPLIED>
<!ELEMENT footnote ANY>
<!ELEMENT biblio ANY>
<!ELEMENT asterism ANY>
<!ELEMENT block-center ANY>
<!ELEMENT two-columns ANY>
<!ELEMENT column ANY>
<!ELEMENT w ANY>

=== thabz/Kalliope/fdirs/segni/andre.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kalliopework SYSTEM "../../data/kalliopework.dtd">
<kalliopework id="andre" author="segni" status="incomplete" type="poetry">
<workhead>
   <title>Andre digte</title>
   <year>?</year>
   <quality>korrektur1</quality>
</workhead>
<workbody>

<text id="segni2002032001">
<head>
   <title>Hujus cum regeret mortales spiritus artus</title>
   <toctitle>Hujus cum regeret mortales spiritus artus</toctitle>
   <indextitle>Hujus cum regeret mortales spiritus artus</indextitle>
   <firstline>Hujus cum regeret mortales spiritus artus</firstline>
   <notes>
      <note>Den italienske maler Antonio da Correggio (1494-1534).</note>
      <note>Digtet citeres af Giorgio Vasari, <i>Vite degli artisti</i> (1. udg. 1647). Læs <a href="http://rubens.anu.edu.au/htdocs/texts/vasari/vasari.correggio.html">Vasaris tekst</a>.</note>
      <note type="credits">Bidrag fra Sven Sørensen.</note>
   </notes>
   <quality>korrektur1</quality>
</head>
<body>
<poetry>
Hujus cum regeret mortales spiritus artus
Pictoris, Charites supplicuere Jovi:
Non alia pingi dextra, Pater alme, rogamus,
Hunc praeter, nulli pingere nos liceat.
Annuit his votis summi regnator olympi,
Et juvenem subito sydera ad alta tulit
Ut posset melius Charitum simulacra referre,
Praesens, et nudas cerneret inde Deas.
</poetry>
</body>
</text>
</workbody>
</kalliopework>

=== thabz/Kalliope/fdirs/chenier/andre.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kalliopework SYSTEM "../../data/kalliopework.dtd">
<kalliopework id="andre" author="chenier" status="incomplete" type="poetry">
<workhead>
   <title>Andre digte</title>
   <quality>korrektur1</quality>
</workhead>
<workbody>

<text id="chenier2018083101">
<head>
   <title>A la liberté</title>
   <firstline>Descends, ô liberté ! fille de la nature</firstline>
   <quality>korrektur1</quality>
</head>
<body>
<poetry>
Descends, ô liberté ! fille de la nature : 
Le peuple a reconquis son pouvoir immortel ;
Sur les pompeux débris de l'antique imposture
Ses mains relèvent ton autel.

Venez, vainqueurs des rois : l'Europe vous contemple ; 
Venez ; sur les faux dieux étendez vos succès ; 
Toi, sainte liberté, viens habiter ce temple ;
Sois la déesse des Français.

Ton aspect réjouit le mont le plus sauvage,
Au milieu des rochers enfante les moissons ;
Embelli par tes mains, le plus affreux rivage 
Rit, environné de glaçons.

Tu doubles les plaisirs, les vertus, le génie ;
L'homme est toujours vainqueur sous tes saints étendards ;
Avant de te connaître, il ignorait la vie : 
Il est créé par tes regards.

Au peuple souverain tous les rois font la guerre ; 
Qu'à tes pieds, ô déesse, ils tombent désormais ! 
Bientôt sur les cercueils des tyrans de la terre 
Les peuples vont jurer la paix.    
</poetry>
</body>
</text>

<text id="chenier2020011001">
<head>
    <title>Le Chant du départ</title>
    <firstline>La victoire en chantant</firstline>
</head>
<body>
<poetry>
La victoire en chantant
Nous ouvre la barrière.
La Liberté guide nos pas.
Et du Nord au Midi
La trompette guerrière
A sonné l'heure des combats.
Tremblez ennemis de la France
Rois ivres de sang et d'orgueil.
Le Peuple souverain s'avance,
Tyrans descendez au cercueil.

    <nonum><i>Refrain</i></nonum>
      La République nous appelle
    Sachons vaincre ou sachons périr
      Un Français doit vivre pour elle
    Pour elle un Français doit mourir.    

De nos yeux maternels ne craignez pas les larmes :
Loin de nous de lâches douleurs !
Nous devons triompher quand vous prenez les armes :
C'est aux rois à verser des pleurs.
Nous vous avons donné la vie,
Guerriers, elle n'est plus à vous ;
Tous vos jours sont à la patrie :
Elle est votre mère avant nous.

Que le fer paternel arme la main des braves ;
Songez à nous au champ de Mars ;
Consacrez dans le sang des rois et des esclaves
Le fer béni par vos vieillards ;
Et, rapportant sous la chaumière
Des blessures et des vertus,
Venez fermer notre paupière
Quand les tyrans ne seront plus.        

Partez, vaillants époux ; les combats sont vos fêtes ;
Partez, modèles des guerriers ;
Nous cueillerons des fleurs pour en ceindre vos têtes :
Nos mains tresserons vos lauriers.
Et, si le temple de mémoire
S'ouvrait à vos mânes vainqueurs,
Nos voix chanteront votre gloire,
Nos flancs porteront vos vengeurs.

Et nous, sœurs des héros, nous qui de l'hyménée
Ignorons les aimables nœuds ;
Si, pour s'unir un jour à notre destinée,
Les citoyens forment des vœux,
Qu'ils reviennent dans nos murailles
Beaux de gloire et de liberté,
Et que leur sang, dans les batailles,
Ait coulé pour l'égalité.

Sur le fer devant Dieu, nous jurons à nos pères,
À nos épouses, à nos sœurs,
À nos représentants, à nos fils, à nos mères,
D'anéantir les oppresseurs :
En tous lieux, dans la nuit profonde,
Plongeant l'infâme royauté,
Les Français donneront au monde
Et la paix et la liberté.        
        
</poetry>
</body>
</text>

</workbody>
</kalliopework>

=== thabz/Kalliope/fdirs/grundtvig/pinsesalmer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kalliopework SYSTEM "../../data/kalliopework.dtd">
<kalliopework id="pinsesalmer" author="grundtvig" status="incomplete" type="poetry">
<workhead>
   <title>Pinsesalmer</title>
   <quality>korrektur1</quality>
</workhead>
<workbody>

<text id="grundtvigpinsesalmera2">
<head>
   <title>Kraften fra det høje</title>
   <toctitle>Kraften fra det høje</toctitle>
   <indextitle>Kraften fra det høje</indextitle>
   <firstline>Kraften fra det høje</firstline>
   <quality>korrektur1</quality>
</head>
<body>
<poetry>
Kraften fra det høje,
Alt som en Ild for Øje,
Med alle Tungers Liflighed
Neddaled til Guds Menighed.
Takker alle Gud for hans Gave!

Kraften fra det høje,
Guds Aand, os sammenføje,
Fra Øst og Vest, fra Syd og Nord,
Til Gjæster ved vor Herres Bord!
Takker alle Gud for hans Gave!

Kraften fra det høje
Os i vort Sind fornøje,
Som Herrens Folk med Himlens Fred,
Udvalgte til Guds Salighed!
Takker alle Gud for hans Gave!
</poetry>
</body>
</text>

<text id="grundtvigpinsesalmera4">
<head>
   <title>Gud Helligaand, vor Igjenføder</title>
   <toctitle>Gud Helligaand, vor Igjenføder</toctitle>
   <indextitle>Gud Helligaand, vor Igjenføder</indextitle>
   <firstline>Gud Helligaand, vor Igjenføder</firstline>
   <quality>korrektur1</quality>
</head>
<body>
<poetry>
Gud Helligaand, vor Igjenføder
Til Børn af ham, som os har skabt,
Til alt hvad Hedninger og Jøder
Ved Synd forbrød, ved Død har tabt!
Vær du vor Tolk, vær du vor Taler!
Vær du vor himmelske Husvaler,
Til vi bli'r ny fra Top til Taa!

Det nye Liv, som hos os svulmer,
Hvor lysteligt at tænke paa!
Den lille Gnist, som i os ulmer
Fra Arilds Tid i Aske graa,
Se hvor den flammer, hvor den tindrer,
og brænder paa alt hvad som hindrer
Nylivets Væxt i Herrens Lys!

Men farefuldt er Levneds-Løbet
Paa Vejen mellem Ilde to,
Hvor evigt Liv for Død er Kjøbet,
Og Støttestaven kun vor Tro,
Saa altid maa det gamle dødes,
Før i dets sted det ny kan fødes,
Som Frelseren af Grav opstod.

Ja, gennem denne Skærsilds Luer
Gaar Vejen til Jerusalem,
Den smalle Sti paa Myretuer
Til Livets Væld og Lysets Hjem,
Og over Porten til Guds-Staden
Med Flamme-Skrift staaer paa Guldpladen:
Bekjend din Tro! Fornægt dig selv!

Det er den snævre Port for Sjælen,
For det i os, som siger "jeg",
Hvis Ære med den dybe Knælen
Indlysende forliges ej;
Skjøndt intet værdt er hvad vi mister,
Os Egenkjærlighed dog frister
Til paa "os selv" at holde fast.

I Kampen hed, hvad kan husvale,
Undtagen, Helligaand! din Trøst
Som Himmel-Dug i dybe Dale
Som Moder-Kjærlighedens Røst?
Vær du vor Tolk! vær du vor Taler!
Vær du vor himmelske Husvaler,
Til vi bli'r ny fra Top til Taa!
</poetry>
</body>
</text>
</workbody>
</kalliopework>

=== thabz/Kalliope/fdirs/krossing/1858.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kalliopework SYSTEM "../../data/kalliopework.dtd">
<kalliopework id="1858" author="krossing" status="incomplete" type="poetry">
<workhead>
   <title>Digte</title>
   <year>1858</year>
   <quality>korrektur1</quality>
</workhead>
<workbody>

<text id="krossing1999031901">
<head>
   <title>Ride, ride, Ranke</title>
   <toctitle>Ride, ride, Ranke</toctitle>
   <indextitle>Ride, ride, Ranke</indextitle>
   <firstline>Ride, ride, Ranke!</firstline>
   <quality>korrektur1</quality>
</head>
<body>
<poetry>
  Ride, ride, Ranke!
Greven er saa højt paa Straa,
Bonden maa med Træsko gaa.
  Ride, ride, Ranke!

  Ride, ride, Ranke!
Junkren paa sin fine Hest,
Som kan dandse, ret gjør Blæst.
  Ride, ride, Ranke!

  Ride, ride, Ranke!
Frøknen sidder let som Fjer,
Som min lille Rytter her.
  Ride, ride, Ranke!

  Ride, ride, Ranke!
Hvorhen skal nu Vejen gaae?
Bedstefar Besøg skal faae.
  Ride, ride, Ranke!

  Ride, ride, Ranke!
Og naar vi saa stige af,
Sige vi: Goddag, Goddag!
  Ride, ride, Ranke!

  Ride, ride, Ranke!
Bedstemoer af Hjertensgrund
Trykker os et Kys paa Mund.
  Ride, ride, Ranke!

  Ride, ride, Ranke!
Tantes Stuedør vil vi
Heller ikke gaae forbi.
  Ride, ride, Ranke!

  Ride, ride, Ranke!
Nu til Onkel i Galop.
Er han hjemme? Ja. Saa stop.
  Ride, ride, Ranke!

  Ride, ride, Ranke!
Men nu er det Aftenstid;
Lille Hest, til Stalden hid.
  Ride, ride, Ranke!

  Ride, ride, Ranke!
Til imorgen staa i Ro.
Havre først: et Kys, ja to.
  Ride, ride, Ranke!
</poetry>
</body>
</text>

<text id="krossing1999031902">
<head>
   <title>Fingrene</title>
   <toctitle>Fingrene</toctitle>
   <indextitle>Fingrene</indextitle>
   <firstline>Søskende jeg kjender fem</firstline>
   <quality>korrektur1</quality>
</head>
<body>
<poetry>
Søskende jeg kjender fem;
Stakkel, som ej kjender dem:
Ved hverandres Side sat
Blev de Mennesket en Skat.

<i>Tommeltot</i> er Patriark,
Lille, buttet, rørig Knark,
Styrer Flokken som Regent,
Ellers var det slet bevendt.

<i>Slikkepot</i> har Tyvsnatur,
Sidder fremmest og paa Luur;
Han er Barnets Pegepind,
Naar det faae sin Fibel ind.

<i>Langemand</i> højt rækker op
Midt i Klyngen med sin Krop;
Naar tilvæds man trækker Krog,
Gavner godt det store Skrog.

<i>Guldbrand</i> har den søde Rang,
Bærer Ringen, gyldentrang;
Om hans Lykke tier Sang,
Ellers Visen blev for lang.

<i>Lille Peter Spillemand,</i>
Ikke meget højner han;
Morer sig saa jevnt og godt,
Som en stakkels Askepot.

Rækker jeg dig alle frem,
Giver du mig dine Fem;
Er et Tryk: Farvel, min Ven!
Og til Velkomst et igjen.
</poetry>
</body>
</text>
</workbody>
</kalliopework>

=== thabz/Kalliope/fdirs/winter/1860.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kalliopework SYSTEM "../../data/kalliopework.dtd">
<kalliopework id="1860" author="winter" status="complete" type="poetry">
<workhead>
    <title>Samlede Digtninger</title>
    <year>1860</year>
    <notes>
        <note>Teksterne følger Christian Winther: <i>Samlede Digtninger</i>, C.A. Reitzels Forlag, Kbh., 1860.</note>
        <note>Udeladt i Kalliope er indtil videre bindene 8-11. Bind 8 og 9 er »Fortællinger i Prosa«, I og II. Bind 10 findes som <a work="winter/1865"><i>Brogede Blade</i> (1865)</a> og bind 11 findes som <a work="winter/1872"><i>En Samling Vers</i> (1872)</a>.</note>
    </notes>
</workhead>
<workbody>
    <subwork ref="1860-1"/>    
    <subwork ref="1860-2"/>    
    <subwork ref="1860-3"/>    
    <subwork ref="1860-4"/>    
    <subwork ref="1860-5"/>    
    <subwork ref="1860-6"/>    
    <subwork ref="1860-7"/>    
</workbody>
</kalliopework>

=== thabz/Kalliope/fdirs/grundtvig/1853.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kalliopework SYSTEM "../../data/kalliopework.dtd">
<kalliopework id="1853" author="grundtvig" status="incomplete" type="poetry">
<workhead>
   <title>Fest-Psalmer</title>
   <year>1853</year>
   <quality>korrektur1</quality>
</workhead>
<workbody>

<text id="grundtvigpinsesalmera3">
<head>
   <title>I al sin Glands nu straaler Solen</title>
   <toctitle>I al sin Glands nu straaler Solen</toctitle>
   <indextitle>I al sin Glands nu straaler Solen</indextitle>
   <firstline>I al sin Glands nu straaler Solen</firstline>
   <quality>korrektur1</quality>
</head>
<body>
<poetry>
I al sin Glands nu straaler Solen,
Livs-Lyset over Naadestolen,
Nu kom vor Pinselilje-Tid,
Nu har vi Sommer skær og blid,
Nu spaar os mer end Englerøst
I <i>Jesu</i> Navn en gylden Høst.

I Sommer-Nattens korte Svale
Slaar højt Fredskovens Nattergale,
Saa alt, hvad Herren kalder sit,
Maa slumre sødt og vaagne blidt,
Maa drømme sødt om Paradis,
Og vaagne til vor Herres Pris.

Det aander himmelsk over Støvet,
Det vifter hjemlig gjennem Løvet,
Det lufter liflig under Sky
Fra Paradis, opladt paa ny,
Og yndig risler ved vor Fod
I Engen Bæk af Livets Flod.

Det volder alt den Aand, som daler,
Det virker alt den Aand, som taler
Ej af sig selv, men os til Trøst,
Af Kiærlighed med Sandheds Røst,
I <i>Ordets</i> Navn, som her blev Kjød
Og foer til Himmels hvid og rød.

Opvaagner alle dybe Toner
Til Pris for Menneskets Forsoner!
Forsamles alle Tungemaal
I Takkesangens Offerskaal!
Istemmer over Herrens Bord
Nu Menighedens fulde Kor!

I <i>Jesu </i>Navn da Tungen gløder
Hos Hedninger saa vel som Jøder;
I <i>Jesus</i>-Navnets Offerskaal
Hensmelter alle Modersmaal;
I <i>Jesu</i> Navn udbryder da
Det evige Halleluja!

Vor Gud og Frelser uden Lige!
Da blomstrer Rosen i dit Rige,
Som Sole vi gaa op og ned
I din enbaarnes Herlighed;
Thi du for Hjertet, vi gav dig,
Gav os med ham dit Himmerig!
</poetry>
</body>
</text>
</workbody>
</kalliopework>
